<?php
// $Id: explorer8_modus.module, v 1.0 2010/04/13 22:14:09 quiptime $

/**
 * @file
 * 
 * With "Explorer8 mode" can be defined as the Internet Explorer 8 to display Web pages that Drupalinstallation.
 */

/**
 * Implement hook_help().
 */
function explorer8_modus_help($path, $arg) {
  switch ($path) {
    case 'admin/config/system/explorer8_modus':
      return t('With "Explorer8 modus" can be defined as the Internet Explorer 8 to display Web pages that Drupalinstallation.');
  }
}

/**
 * Implement hook_init().
 */
function explorer8_modus_init() {
  explorer8_modus_header();
}

/**
 * Implement hook_permission().
 */
function explorer8_modus_permission() {
  return array(
    'administer explorer8 modus' => array(
      'title' => t('Administer explorer8 modus'),
      'description' => t('Define Internet Explorer 8 modus to display Web pages.'),
    ),
  );
}

/**
 * Implement hook_menu().
 */
function explorer8_modus_menu() {
  $items = array();
  $items['admin/config/system/explorer8_modus'] = array(
    'title' => 'Internet Explorer 8 modus',
    'description' => 'Setting the document compatibility mode of the Internet Explorer 8th.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('explorer8_modus_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer explorer8 modus'),
    'file' => 'explorer8_modus.admin.inc',
  );
  return $items;
}

/**
 * Set the meta tag.
 */
function explorer8_modus_header() {
  if (variable_get('explorer8_modus_setting', '') == 'IE=8') {
    return '';
  }
  else {
    // Set weight to make sure that 'X-UA-Compatible' have second tag position.
    $element = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'http-equiv' => 'X-UA-Compatible',
        'content' => variable_get('explorer8_modus_setting', 'IE=8'),
      ),
      '#weight' => -999,
    );
    drupal_add_html_head($element, 'explorer8_modus_header');
  }
}
