<?php
// $Id: explorer8_modus.module, v 1.0 2009/07/20 19:37:34 quiptime $

/**
 * @file
 *
 * With "Explorer8 mode" can be defined as the Internet Explorer 8 to display Web pages that Drupalinstallation.
 */

/**
 * Implement hook_help().
 */
function explorer8_modus_help($path, $arg) {
  switch ($path) {
    case 'admin/settings/explorer8_modus':
      return t('With "Explorer 8 modus" can be defined as the Internet Explorer 8 to display Web pages that Drupalinstallation.');
  }
}

/**
 * Implement hook_init().
 */
function explorer8_modus_init() {
  _explorer8_modus_header();
}

/**
 * Implement hook_permission().
 */
function explorer8_modus_permission() {
  return array(
    'administer explorer8 modus' => array(
      'title' => t('Administer explorer8 modus'),
      'description' => t('Define Internet Explorer 8 modus to display Web pages.'),
    ),
  );
}

/**
 * Implement hook_menu().
 */
function explorer8_modus_menu() {
  $items = array();
  $items['admin/settings/explorer8_modus'] = array(
    'title' => 'Internet Explorer 8 modus',
    'description' => 'Setting the document compatibility mode of the Internet Explorer 8th.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('explorer8_modus_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer explorer8 modus'),
    'file' => 'explorer8_modus.admin.inc',
  );
  return $items;
}

/**
 * Help function.
 */
function _explorer8_modus_header() {
  if (variable_get('explorer8_modus_setting', '') == 'IE=8') {
    return '';
  }
  else {
    $data = '<meta http-equiv="X-UA-Compatible" content="' . variable_get('explorer8_modus_setting', 'IE=8') . '" />';
    drupal_add_html_head($data);
  }
}
